name: prokis
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  timer_builder: ^1.3.0

  lazy_load_scrollview: ^1.0.1

  webview_flutter: ^0.3.4

  auto_size_text: ^0.0.2

  toast: ^0.1.3

  sqflite: ^1.3.0

  intl: ^0.16.1

  path_provider: ^1.6.24
  provider: ^4.3.2+2
  path_provider_macos: ^0.0.1
  path_provider_windows: ^0.0.4+3

  charts_flutter: ^0.9.0

  progress_dialog: ^1.2.0

  timezone: ^0.5.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/images/settings_icon.png
  - assets/images/giris_ekran_arkaplan.png
  - assets/images/kurulum_fan_icon.png
  - assets/images/kurulum_klepe_icon.png
  - assets/images/kurulum_ped_icon.png
  - assets/images/kurulum_isisensor_icon.png
  - assets/images/kurulum_bacafan_icon.png
  - assets/images/kurulum_airinlet_icon.png
  - assets/images/kurulum_isitici_icon.png
  - assets/images/kurulum_isitici_kucuk_icon.png
  - assets/images/kurulum_sirkfan_icon.png
  - assets/images/kurulum_sirkfan_kucuk_icon.png
  - assets/images/kurulum_silo_icon.png
  - assets/images/kurulum_aydinlatma_icon.png
  - assets/images/kurulum_aydinlatma_icon1.png
  - assets/images/kurulum_yemleme_icon.png
  - assets/images/kurulum_sayac_icon.png
  - assets/images/ky_tf_klasik_icon.png
  - assets/images/ky_tf_lineer_icon.png
  - assets/images/ky_tf_pid_icon.png
  - assets/images/ky_tf_pid_icon_grey.png
  - assets/images/ky_mh_klasik_icon.png
  - assets/images/ky_mh_agirlik_icon.png
  - assets/images/ky_mh_hacim_icon.png
  - assets/images/ky_klp_klasik_icon.png
  - assets/images/ky_klp_tunel_icon.png
  - assets/images/kumes_bina_uzunluk_icon.png
  - assets/images/fan_on_gorunuz_icon.png
  - assets/images/soru_isareti.png
  - assets/images/duvar_icon.png
  - assets/images/deger_artir_icon.png
  - assets/images/deger_dusur_icon.png
  - assets/images/onarka_duvar_gri_icon.png
  - assets/images/onarka_duvar_gri_icon1.jpg
  - assets/images/sagsol_duvar_gri_icon.png
  - assets/images/sagsol_duvar_gri_icon1.jpg
  - assets/images/klepe_harita_icon.png
  - assets/images/ped_harita_icon.png
  - assets/images/bina_catisiz_ust_gorunum.png
  - assets/images/harita_isi_sensor_icon.png
  - assets/images/harita_isi_sensor_kucuk_icon.png
  - assets/images/bina_perspektif_gorunum.png
  - assets/images/bina_catili_ust_gorunum.png
  - assets/images/harita_bacafan_icon.png
  - assets/images/kurulum_airinlet_icon.png
  - assets/images/kurulum_isitici_icon.png
  - assets/images/silo_harita.png
  - assets/images/tem_hum_icon.png
  - assets/images/tem_hum_small_icon.png
  - assets/images/cooling_icon.png
  - assets/images/cooling_small_icon.png
  - assets/images/heating_icon.png
  - assets/images/klepe_icon2.png
  - assets/images/klepe_icon.png
  - assets/images/klepe_small_icon.png
  - assets/images/minvent_icon.png
  - assets/images/mancontrol_icon.png
  - assets/images/mancontrol_icon_red.png
  - assets/images/settings_icon.png
  - assets/images/settings_small_icon.png
  - assets/images/wizard_icon.png
  - assets/images/izleme_icon.png
  - assets/images/izleme_small_icon.png
  - assets/images/datalog_chart_icon.png
  - assets/images/datalog_chart_small_icon.png
  - assets/images/kontrol_icon.png
  - assets/images/kontrol_small_icon.png
  - assets/images/alarm_ayarlari_icon.png
  - assets/images/alarm_ayarlari_small_icon.png
  - assets/images/aydinlatma_icon.png
  - assets/images/aydinlatma_small_icon.png
  - assets/images/silo_icon.png
  - assets/images/diagram_lineer_capraz.jpg
  - assets/images/diagram_lineer_normal.jpg
  - assets/images/diagram_klasik_normal.jpg
  - assets/images/diagram_klasik_capraz.jpg
  - assets/images/diagram_pid_normal.jpg
  - assets/images/diagram_pid_capraz.jpg
  - assets/images/diagram_klepe_prob_kontrol.jpg
  - assets/images/acikmavi_oval_icon.png
  - assets/images/turkuaz_oval_icon.png
  - assets/images/feeding_icon.png
  - assets/images/feeding_small_icon.png
  - assets/images/diagram_klepe_klasik1.jpg
  - assets/images/diagram_klepe_klasik2.jpg
  - assets/images/diagram_klepe_tunel.jpg
  - assets/images/diagram_sogutma_civbro.jpg
  - assets/images/diagram_isitma.jpg
  - assets/images/diagram_mh_klasik.jpg
  - assets/images/sagsol_duvar_icon.jpg
  - assets/images/onarka_duvar_icon.jpg
  - assets/images/sagsol_duvar_gri_icon.png
  - assets/images/onarka_duvar_gri_icon.png
  - assets/images/calibration_icon.png
  - assets/images/calibration_icon.png
  - assets/images/cati_icon.png
  - assets/images/kalibrasyon_icon.png
  - assets/images/kalibrasyon_small_icon.png
  - assets/images/su_silo_icon.png
  - assets/images/diger_ops_icon.png
  - assets/images/diger_ops_small_icon.png
  - assets/images/suru_icon.png
  - assets/images/suru_small_icon.png
  - assets/images/kurulum_icon.png
  - assets/images/kurulum_small_icon.png
  - assets/images/saat_tarih_ayar_icon.png
  - assets/images/saat_tarih_ayar_small_icon.png
  - assets/images/giris_rotate_icon.png
  - assets/images/bfan_rotate_icon.png
  - assets/images/giris_sabit_icon.png
  - assets/images/ped_izleme_icon_off.png
  - assets/images/ped_izleme_icon_on.png
  - assets/images/silo_izleme_icon.png
  - assets/images/software_icon.png
  - assets/images/chart_icon.png
  - assets/images/datalog_icon.png
  - assets/images/datalog_small_icon.png
  - assets/images/chart_icon_small.png
  - assets/images/software_small_icon.png
  - assets/images/sistem_start_stop_icon.png
  - assets/images/sistem_start_stop_small_icon.png
  - assets/images/fire_animation.gif

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:



  fonts:
     - family: Kelly Slab
       fonts:
         - asset: assets/fonts/KellySlab-Regular.ttf
           weight: 700

     - family: Audio wide
       fonts:
         - asset: assets/fonts/Audiowide-Regular.ttf
           weight: 700


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
